<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ThreadTest extends TestCase
{

    use DatabaseMigrations;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread=create('App\Thread');
    }

    /** @test */
    public function a_thread_has_replies()
    {

        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection',   $this->thread->replies);
    }

    /** @test */
    public function a_thread_have_creator()
    {

        $this->assertInstanceOf('App\User', $this->thread->creator);
    }


    /** @test */
    public function a_thread_belongs_to_channel(){

        $this->assertInstanceOf('App\Channel', $this->thread->channel);

    }


}


